# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7a14662dd66d19abe28d773f3f1f7c70c5524f6f29285ee1c83bed96ee3b3e882547bdcfae7dbe0723b60ba602a8dd8701785444bdcb61615d21e46ee07711

test:
  secret_key_base: 1505c27faab9be92bc282c885a8b26ef452e0f43dfdac0ae3aa81fc5a1fa576f808fbcc7f1d8854ff06432e583f418054762f5f777051982f6e0235f6e370f34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
